### PR TITLE
Upgrade to gemstash revision 554df9cde684ed427496dfc37605243b66c36f57

### PR DESCRIPTION
**Pull request by juleea**

### CODE REVIEW

**Comment by juleea** [comment]
@kurtzur so is the easiest way to deploy this by manually building the container?

**Comment by juleea** [comment]
cc @seanjfellows

**Comment by kurtzur** [comment]
@juleea yeah I think so, followed by the steps I mentioned on Slack

**Comment by kurtzur** [comment]
@zp-alfred approve

**Comment by kurtzur** [comment]
@zp-alfred accept

**Comment by zp-alfred** [comment]
Accepted by kurtzur!

**Pull request merged**
